# site settings
title: Welcome to
subtitle: Miaoyu's World
email: xiaotuoxie616@gmail.com
description: 一切都是最好的安排
baseurl: "/miaoyu-blog" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 91 Mansfiled St
city: New Haven
state: CT
country: United States of America
phone: (805) 490-9018

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/miaoyuyang
  Instagram: https://www.instagram.com/miaoyu.yang.1
  LinkedIn: 
  TikTok(China): https://v.douyin.com/6ymgq4u

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
